//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input System/UIInputSystem.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UIInputSystem: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UIInputSystem()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UIInputSystem"",
    ""maps"": [
        {
            ""name"": ""TitleScreen"",
            ""id"": ""40c34f7b-cd48-4294-8f63-99826652182a"",
            ""actions"": [
                {
                    ""name"": ""Graphic"",
                    ""type"": ""Button"",
                    ""id"": ""6ebc16e7-987b-4a29-9e05-09ce465e43e0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1adbe01b-0f5c-449b-ab47-cee5665ee3e6"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Graphic"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // TitleScreen
        m_TitleScreen = asset.FindActionMap("TitleScreen", throwIfNotFound: true);
        m_TitleScreen_Graphic = m_TitleScreen.FindAction("Graphic", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // TitleScreen
    private readonly InputActionMap m_TitleScreen;
    private List<ITitleScreenActions> m_TitleScreenActionsCallbackInterfaces = new List<ITitleScreenActions>();
    private readonly InputAction m_TitleScreen_Graphic;
    public struct TitleScreenActions
    {
        private @UIInputSystem m_Wrapper;
        public TitleScreenActions(@UIInputSystem wrapper) { m_Wrapper = wrapper; }
        public InputAction @Graphic => m_Wrapper.m_TitleScreen_Graphic;
        public InputActionMap Get() { return m_Wrapper.m_TitleScreen; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TitleScreenActions set) { return set.Get(); }
        public void AddCallbacks(ITitleScreenActions instance)
        {
            if (instance == null || m_Wrapper.m_TitleScreenActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TitleScreenActionsCallbackInterfaces.Add(instance);
            @Graphic.started += instance.OnGraphic;
            @Graphic.performed += instance.OnGraphic;
            @Graphic.canceled += instance.OnGraphic;
        }

        private void UnregisterCallbacks(ITitleScreenActions instance)
        {
            @Graphic.started -= instance.OnGraphic;
            @Graphic.performed -= instance.OnGraphic;
            @Graphic.canceled -= instance.OnGraphic;
        }

        public void RemoveCallbacks(ITitleScreenActions instance)
        {
            if (m_Wrapper.m_TitleScreenActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITitleScreenActions instance)
        {
            foreach (var item in m_Wrapper.m_TitleScreenActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TitleScreenActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TitleScreenActions @TitleScreen => new TitleScreenActions(this);
    public interface ITitleScreenActions
    {
        void OnGraphic(InputAction.CallbackContext context);
    }
}
